name: telegram_link
description: simple library for generating telegram links. It is possible to generate links with number or username
version: 0.0.2-pre
repository: https://github.com/rickypid/telegram_link

environment:
  sdk: '>=2.15.1 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0