name: telegram_link
description: simple library for generating telegram links. It is possible to generate links with number or username
version: 1.0.0
repository: https://github.com/rickypid/telegram_link

environment:
  sdk: '>=2.17.1 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  import_sorter: ^4.6.0
  test: ^1.16.0